postgresql:
  enabled: false

externalDatabase:
  host: odoo-postgresql
  port: 5432
  name: odoo
  user: odoo
  password: "changeme123!"

replicaCount: 1

odoo:
  init:
    enabled: false
    modules: base,web
  update:
    maintenancePage: false
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: odoo.mspr2
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: odoo-tls-secret
    hosts:
      - odoo.mspr2
