apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud.conf: |
    [Global]
    auth-url=changeme
    username=changeme
    password=changeme
    region=changeme
    tenant-id=changeme
    domain-name=changeme

    [BlockStorage]
    ignore-volume-az=true